<template lang="pug">
div.post-container
  menu-page.menu-blog
  div.parallax
      div.img
        img(:src="bg")
        div.parallax-content
          div.content.animate-fade
            h1.logo
              q-icon(name="mdi-gavel")
              | LEGAL AI
            h2.page-title {{$t('post.name')}}
  div.post-inside
    h1 Artificial Intelligence applied to law: how we constructed Dra. Luzia, the first platform in Brazil with machine learning applied to judicial decisions (Part 1)
    article
      p.preface Abstract— The need for technology applied to the legal sector has been a very relevant issue in the Brazilian scenario. The volume of processes is huge and the traditional methods of process analysis and execution no longer account for the demand. There is an increasing tendency for automation, the electronic process is a reality and the next step is the application of machine learning techniques to process the enormous amount of data generated by the Judiciary. The process was physical, then turned digital, we inaugurated the next phase: intelligence on the mass litigations. The amount of Brazilian lawsuits shows a crisis scenario that is, at the same time, an important generator of opportunities. In this article, we show how we developed Dra. Luzia, who was trained to make decisions in mass litigations. To do so, we elucidate how data mining and the application of machine learning, including deep learning, were applied in the development of the Artificial Intelligence platform Dra. Luzia. We believe that the Brazilian Judiciary will begin to use IA soon. This will directly impact the speed of procedural steps.

      h2 I - Introduction

      p Brazilian Judiciary is enormous. It is composed by more than eighteen thousand judges and hundreds of thousands of public servants 1 [1], and there are 91 appellate, higher and supreme courts, being the State Court of São Paulo the biggest court in the world. Furthermore, there is a National Council of Justice (CNJ) 2 , charged with non-jurisdictional attributions. In 2016, the total expenditure with the judicial system was of R$ 3 84.8 billion[1]. Despite all that figures, a lawsuit usually takes years until its completion, being the Judiciary widely regarded as slow. Does this situation has a solution? How did we arrive at such point?

      p Maybe it is a legacy from an old Brazil, whose state apparatus was built upon an extremely inefficient, complex and corrupt bureaucracy, stuck in infeasible, incongruent and uneven statutes. New statutes 4 , mainly the ones from 2015 – New Civil Procedure Code (Lei n o 13.105/15), Mediation Act (Lei n o 13.140/15) and New Arbitration (Lei n o 13.129/15) – try to improve this scenario. However, new law alone, without a cultural change, will not be able to remove from the Judiciary the unison centrality of conflict resolution.

      p One of the legacies of the Modern State is the state monopoly in the distribution of justice. Since its establish- ment, judicial litigation is the only way of conflict resolution allowed in the legal order. Self-defence was dismissed, but the access to Judiciary was always limited.

      p One of the legacies of the Modern State is the state monopoly in the distribution of justice. Since its establish- ment, judicial litigation is the only way of conflict resolution allowed in the legal order. Self-defence was dismissed, but the access to Judiciary was always limited.

      p The world was different in 1988. How Werneck Vianna recollects [2], the Constitution itself was part of the process of transition from authoritarianism to democracy, and not one of its outcomes. This had its effects, in the following decades, in the exponential raise in the volume of new lawsuits filed in the judicial system. Insofar as the valor of access begins to be present in the core of people, Brazil starts to take its problems to court.

      p In 1988, the estimated volume of Brazilian lawsuits was below 400 thousand. About one decade later, the measure- ment noted a leap, being estimated now between 2 and 6 million lawsuits. In 2003, the first year of the Justiça em números 6 (Justice in numbers) report, in the Justices of the Member-States alone there were 3 million ongoing lawsuits and more 3.7 million were initiated that year. The total of processes was already above 10 million in 2003. Five years later, in 2008, we had already 70.1 million of lawsuits. In 2014, we surpassed the milestone of 100 million 7 .

      p The good news is that the Judiciary is being able to follow this volume: the number of initiating processes is practically identical to the number of tried processes in the last 3 years. According to successive reports Justiça em números, respectively in relation to 2014, 2015 and 2016, from 21 to 28.8 million of new cases arrived to the Judiciary all these years (practically the same number of trials, especially in 2015 and 2016). To this number are added the respective 73 to 79.6 million of lawsuits in inventory in Brazilian courts, regarding the same period.

      p The result is the number of more than 100 million of ongoing lawsuits in Brazil in the last 3 years. In 2016, 28.82 million of processes began and 28.87 million were terminated, while the inventory had around 78.97 million [1].

      p For ideological reasons, we completely opened the en- trance door of the Judiciary from 1988 on. No one has never thought about reaching this volume... we did not think in the exit door. Now we need to solve the exit, the slowness, the inventory.

      p Besides the great volume, there is also a daunting slowness in the judiciary context. The average time length of pending processes in the Judiciary of the Member-States is of 5 years and 4 months in judicial cognition, 2 years and 6 months in appellate jurisdiction and 7 years and 6 months in execution [1]. In non-pending processes, is of 3 years and 1 month in judicial cognition, 1 year in appellate jurisdiction and 3 years and 4 months in execution. This data confirm that the average citizen, when he or she has their rights subtracted, will wait during a considerable lapse of time to receive “justice”: the adjudication

      p The exaggerated duration until the resolution of the case distorts the system of Justice, imposing to the creditor the burden of time of judicial slowness 8 . The guilty, the debtor, always is benefited by the delay. What also reflects negatively in the confidence of the citizens in the national judiciary system.

      p Besides the dilatoriness, an important reflex of an exa- cerbated system of justice is the rise of its costs. The total expenditure with Brazilian judicial system in 2003 was of R$ 14 billion of reais, of which approximately 86% of this amount, or R$ 12 billion, was with personnel [4]. The expenses with workforce for maintenance and expansion of the service alone, in 2016, was of R$ 75.94 billion (or 89.5%), of a total of expenses in the order of R$ 84.8 billion [1]. The spending with personnel has had a significant and constant rise during time.

      p Besides the dilatoriness, an important reflex of an exa- cerbated system of justice is the rise of its costs. The total expenditure with Brazilian judicial system in 2003 was of R$ 14 billion of reais, of which approximately 86% of this amount, or R$ 12 billion, was with personnel [4]. The expenses with workforce for maintenance and expansion of the service alone, in 2016, was of R$ 75.94 billion (or 89.5%), of a total of expenses in the order of R$ 84.8 billion [1]. The spending with personnel has had a significant and constant rise during time.

      p In a close examination of the data of 2016, we see that R$ 2.4 billion were spent with information technology [1]. What means that expenses with technology and innovation was below 3% of the total expenditure of national Judiciary. When we remember the crescent rise of the volume of new processes and the size of the inventory, the direct conclusion is that this count does not and will not close. The enlargement of the service without the use of scalable innovative technology tends to maintain the track record of unreasonable growth of public expenditure with personnel. In its great majority, the relevant group of professionals who operate in the Judiciary engage with a lot of diligence to solve with efficiency, celerity and passion their work. Nonetheless, we believe that the current volume of processes prevent a solution without the support of technology.

      p The presented barriers to the existence of an effective Jus- tice started to cause a reaction by the public authorities. One of the important ways of solving this problem is the multido- ors system stimulated by the mentioned new statutes of 2015. This system aims to share with society the responsibility of dispute resolution, be it through judicial and extrajudicial mediation – including through digital means, what promoted the creation of startups that propose to realize ODR (on- line dispute resolution) –[5], be it through stimulation of arbitration. There is still the reform of procedural rules, with the adoption of procedural mechanisms of mass litigation, as the “incidente de resolução de demandas repetitivas” (Incident of Resolution of Repetitive Causes), among many others.

      p Another way of solving the system of justice is the use of artificial intelligence (and other forms of technological innovation, like the analysis of complex networtks). AI may be used for the execution of repetitive tasks, be it on the side of the litigators and their respective lawyers, be it on the side of Judiciary in repetitive tasks, especially in the non-decision-making ones (which delay the progress of the lawsuit), but also giving support in the decision-making ones.

      p In this paper we aim to explain the construction, including its steps and challenges, of the first platform with applied AI to judicial decisions to support the petitioning in mass litigations. It was the perception of the huge potential of machine learning technology (including deep learning) in mass litigation that stimulated us to publish it.

      p In this paper we aim to explain the construction, including its steps and challenges, of the first platform with applied AI to judicial decisions to support the petitioning in mass litigations. It was the perception of the huge potential of machine learning technology (including deep learning) in mass litigation that stimulated us to publish it.

      p The courts and the great litigants – Public Power, banks, insurance companies, telecom companies, e-commerce, etc. – will be the biggest beneficiaries of this technology 10 . There are, also, strong applications in mass administrative litigation, like causes in INSS 11 , in DETRANs 12 , etc. The impact of technology is very potent in legal departments with mass litigation, be it judiciary or administrative, public or private, including companies that seek to better allocate their resources when dealing with actual or potential lawsuits.

      h2 II - First Steps

      p The first step was to adequately define the initial problem to be addressed. For this, defining the task (restricting the application object of machine learning) was essential. There is no artificial general intelligence, as Manisha Salecha explains [6]. We then chose the largest volume of Brazilian lawsuits: the tax foreclosures, which accumulate in their various inefficiency steps 13 more than 32 millions cases (above 30% of total court cases).

      p Relevant data of the analyzed domain (legal field) are the essential basis necessary for the application of Artificial Intelligence (AI). It takes a great deal of commitment from technology developers and domain experts to aggregate the relevant volume and diversity of information and to structure them consistently, making them useful for machine learning procedures.

      p Once we have defined the niche and the data on which we were going to work with, we proceeded to the phase of observation and data structuring. Data extraction is an initially costly task and performed according to the demand of the solution, since the data will rarely be available in an ideal format and usable by the system.

      p Therefore, a suitable procedure is to aggregate the data un- der the Extract-Transform-Load strategy, which performs the tasks of identifying relevant information in the data source, extracting this information, personalizing and integrating this information with various sources, based on pre-defined rules and load them into some sort structured storage [7].

      p All the information used for machine learning procedures by Dra. Luzia platform had to go through this process to become useful to the learning operations performed later. We had to turn lawsuits into data that could be interpreted by the machine.

      p Due to the need of the ML application for a large amount of data, such a task becomes unfeasible to be done manually, so that the ETL strategy used was encoded in automated mechanisms and the massively extracted data were structu- red and processed under an efficient quality control, thus optimizing the execution of operations done by the future platform, Dra. Luzia.

      i.mini-title A. Dataset

      p Information used by Dra. Luzia’s first stage was extracted from public data and available from open sources. The sour- ces that allow greater data capture are web pages of public organs and Courts in general, which provide unrestricted access to their cases. It would be better if it was open data, but failing that, the team extracts massively such public data - which increases the cost of the project, but does not make it unfeasible.

      i.mini-title B. Extract Step

      p The technique of obtaining unstructured data available on a web page is called data scraping, which is the programmatic analysis of a data source to be able to access one or more online sources to search for available information, usually openly in the source code from page.

      p Web data scraping is performed from a set of techniques that automatically obtain information from a site rather than manually copying it. The scraper seeks a set of information to extract and aggregate, transforming unstructured data into something that can be saved to databases in a structured way 15 . In this step we already use some techniques of Natural Language Processing.

      p The source code of a Web page consists of tags that make up each element in its visual interface. From the detection of these structures, content of each Web element, one can obtain the specific data desired by the extraction code.

      p A procedure similar to what has been done with the extraction of DJEs (Electronic Justice Journal) or court moves, only more profound and related.

      i.mini-title C. Transform Step

      p Data transformation is a pre-processing task that results in what will become the information used by the machine learning system. This stage was optimized, being executed simultaneously to the extraction. The extracted data of the web pages already received an initial processing to fit the structuring in JSON format [8].

      p Again, Natural Language Processing techniques are used so that errors are corrected immediately, avoiding another processing of the database. With this conversion to the desired format in a platform-modeled structure, each process is saved as a JSON-format file and a certain set of files.

      p The primary storage and structuring format chosen was JSON because of its increasingly universal interpretability and compatibility with various non-relational database tech- nologies - NoSQL [9] -, allowing for greater scalability using this data.

      post-author(
        authorName="Ricardo Fernandes",
        :authorPhoto="ricardo",
        authorRole="Pós-PH.D. em Informática Jurídica no CODEX (Stanford)",
        date="October 13 2017",
        timeLecture="6"
      )
      post-author(
        authorName="Danilo Barros Mendes",
        :authorPhoto="danilo",
        authorRole="Graduando em Engenharia de Software pela UnB",
        date="October 13 2017",
        timeLecture="6"
      )
      post-author(
        authorName="Hugo Honda",
        :authorPhoto="placeholder",
        authorRole="Graduando em Ciência da Computação pela UnB",
        date="October 13 2017",
        timeLecture="6"
      )
      post-author(
        authorName="André Guedes",
        :authorPhoto="placeholder",
        authorRole="Engenheiro de Software (UnB)",
        date="October 13 2017",
        timeLecture="6"
      )
  footer-page
</template>

<script>
import MenuPage from '../components/menu/Menu'
import FooterPage from '../components/general/FooterPage'
import PostAuthor from '../components/posts/PostAuthor'

export default {
  name: 'Preconceito',
  components: {
    MenuPage,
    FooterPage,
    PostAuthor
  },
  props: {
    postId: {
      type: String
    }
  },
  computed: {
    bg () {
      return require('../assets/img/code-dra-luzia.jpg')
    },
    ricardo () {
      return require('../assets/img/ricardo.jpg')
    },
    danilo () {
      return require('../assets/img/danilos.jpeg')
    },
    placeholder () {
      return require('../assets/img/placeholder.jpg')
    }
  }
}

</script>

<style lang="stylus" scoped>
@import '~variables'
.post-container
  display flex
  flex-direction column
  background white
  @media (max-width: 414px)
    padding-top 70px
.menu-blog
  @media (max-width: 414px)
    position fixed
    z-index 1
    top 0
.post-inside
  width 35%
  margin 0 auto
  padding 40px 0 60px 0
  @media (max-width: 1530px)
    width 60%
  @media (max-width: 768px)
    width 88%
    padding 20px 0 60px 0
  @media (max-width: 414px)
    width 85%
    padding 20px 0 60px 0
  h1
    font-weight 800
    font-size 3rem
    line-height 3.4rem
    letter-spacing -0.3px
    display flex
    max-width calc(100% - 15px)
    word-break break-word
    color $grey-9
    @media (max-width: 414px)
      font-size 2.5rem
      line-height 2.9rem
  article
    p
      font-size 21px
      line-height 1.58
      letter-spacing -.003em
      word-break break-word
      word-wrap break-word
      color $grey-9
      font-family Georgia, Cambria, 'Times New Roman', Times, serif
      font-weight 500
    .preface
    .with-divisor
      &:after
        content ''
        display block
        background $grey-9
        margin 40px 0
        width 60px
        height 2px
    h2
      font-weight 800
      font-size 1.7rem
      line-height 2rem
      letter-spacing -0.3px
      display flex
      max-width calc(100% - 15px)
      word-break break-word
      color $grey-9
    img
      margin 0 auto
      display block
      @media (max-width: 768px)
        max-width 660px
      @media (max-width: 414px)
        max-width 320px
    h6
      font-size 16px
      line-height 1
      letter-spacing -0.2px
      word-break break-word
      word-wrap break-word
      color $grey-9
      font-family Georgia, Cambria, 'Times New Roman', Times, serif
      font-weight 500
      display block
      width 100%
      text-align center
      margin 20px 0 40px 0
    blockquote
      font-size 24px
      line-height 1.4
      letter-spacing -.003em
      word-break break-word
      word-wrap break-word
      color $grey-9
      font-family Georgia, Cambria, 'Times New Roman', Times, serif
      font-weight 500
      margin 40px 0
      font-style italic
  a
    color $grey-9
    $:visited
      color $grey-9
  .mini-title
    color $grey-9
    font-size 20px
    font-weight bold
    margin-bottom 15px
    display block
.img
  margin-top 60px
  position relative
  width 100%
  height 200px
  overflow hidden
  display flex
  flex-direction column
  align-items center
  justify-content center
  @media (max-width: 670px)
    height 160px
  img
    width 100%
.parallax-content
  position absolute
  top 0
  width 100%
  height 100%
  // background rgba(35, 35, 35, 0.8)
  background linear-gradient(to right, $primary, rgba(34, 33, 126, 0.97), transparent)
  // background linear-gradient(to right, $primary, transparent)
  display flex
  flex-direction column
.content
  width 100%
  max-width 1233px
  margin 0 auto
  display flex
  // justify-content center
  align-items center
  // flex-direction column
  height 100%
  @media (max-width: 1300px)
    padding 0 25px
  @media (max-width: 670px)
    justify-content center
  @media (max-width: 460px)
    flex-direction column
.content
  width 100%
  max-width 1233px
  margin 0 auto
  display flex
  // justify-content center
  align-items center
  // flex-direction column
  height 100%
  @media (max-width: 1300px)
    padding 0 25px
  @media (max-width: 670px)
    justify-content center
  @media (max-width: 460px)
    flex-direction column
.logo
  margin 0
  font-size 60px
  color white
  font-weight bold
  @media (max-width: 1160px)
    font-size 50px
  @media (max-width: 670px)
    font-size 35px
  .q-icon
    margin-top -22px
    margin-right 10px
    font-size 70px
    @media (max-width: 1160px)
      font-size 60px
    @media (max-width: 670px)
      font-size 45px
.page-title
  color white
  margin 0
  font-size 50px
  line-height 56px
  margin-left 25px
  @media (max-width: 1160px)
    font-size 38px
    margin-left 20px
  @media (max-width: 670px)
    font-size 32px
    line-height 36px
    margin-top 3px
    margin-left 15px
  @media (max-width: 460px)
    margin-left 0
</style>
